# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef7676790895a622054c65423d8e73718494d41bce09c4d4dbf27323b7d806bb6506193279b89ffa23d149dcefb8d14d475e11fda2b34c6a0e9018d0f1d4e321

test:
  secret_key_base: 564d48641307644c9d6a5351e65b6ebd7555c6db2a42199ecc14585e9660b5cab3e59e84c4451de548e860b31dfeb64cf8fcc80e62f94489b4d90b14bee619b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
